on: [push]

jobs:
  run_specs:
    runs-on: ubuntu-latest
    name: Build raft server image
    steps:  
      - uses: actions/checkout@v2
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: ghcr.io/ukd1/raft-for-beginners-too-json-server:latest